// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crawl-loading/GlassPulse.tsx": () => import("../components/mockups/crawl-loading/GlassPulse.tsx"),
  "./components/mockups/crawl-loading/MissionControl.tsx": () => import("../components/mockups/crawl-loading/MissionControl.tsx"),
  "./components/mockups/crawl-loading/TerminalDark.tsx": () => import("../components/mockups/crawl-loading/TerminalDark.tsx"),
  "./components/mockups/geo-comparison/CrawlabilityTable.tsx": () => import("../components/mockups/geo-comparison/CrawlabilityTable.tsx"),
  "./components/mockups/landing/GeoLanding.tsx": () => import("../components/mockups/landing/GeoLanding.tsx"),
  "./components/mockups/segment-card/SegmentResultCard.tsx": () => import("../components/mockups/segment-card/SegmentResultCard.tsx")
};
