// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/button-preview/AnalyseButton.tsx": () => import("../components/mockups/button-preview/AnalyseButton.tsx"),
  "./components/mockups/crawl-loading/GlassPulse.tsx": () => import("../components/mockups/crawl-loading/GlassPulse.tsx"),
  "./components/mockups/crawl-loading/MissionControl.tsx": () => import("../components/mockups/crawl-loading/MissionControl.tsx"),
  "./components/mockups/crawl-loading/TerminalDark.tsx": () => import("../components/mockups/crawl-loading/TerminalDark.tsx"),
  "./components/mockups/directory/DirectoryListing.tsx": () => import("../components/mockups/directory/DirectoryListing.tsx"),
  "./components/mockups/directory/QueryPage.tsx": () => import("../components/mockups/directory/QueryPage.tsx"),
  "./components/mockups/geo-comparison/CrawlabilityTable.tsx": () => import("../components/mockups/geo-comparison/CrawlabilityTable.tsx"),
  "./components/mockups/recent-tiles/DetailCards.tsx": () => import("../components/mockups/recent-tiles/DetailCards.tsx"),
  "./components/mockups/recent-tiles/GridCards.tsx": () => import("../components/mockups/recent-tiles/GridCards.tsx"),
  "./components/mockups/recent-tiles/ScrollStrip.tsx": () => import("../components/mockups/recent-tiles/ScrollStrip.tsx"),
  "./components/mockups/report-format/IntelligenceDashboard.tsx": () => import("../components/mockups/report-format/IntelligenceDashboard.tsx"),
  "./components/mockups/report-format/StructuredSections.tsx": () => import("../components/mockups/report-format/StructuredSections.tsx"),
  "./components/mockups/landing/GeoLanding.tsx": () => import("../components/mockups/landing/GeoLanding.tsx"),
  "./components/mockups/segment-anim/AgentActivity.tsx": () => import("../components/mockups/segment-anim/AgentActivity.tsx"),
  "./components/mockups/segment-anim/DispatchFeed.tsx": () => import("../components/mockups/segment-anim/DispatchFeed.tsx"),
  "./components/mockups/segment-anim/EngineRace.tsx": () => import("../components/mockups/segment-anim/EngineRace.tsx"),
  "./components/mockups/segment-card/SegmentResultCard.tsx": () => import("../components/mockups/segment-card/SegmentResultCard.tsx"),
  "./components/mockups/session-summary/CompactStrip.tsx": () => import("../components/mockups/session-summary/CompactStrip.tsx"),
  "./components/mockups/session-summary/ScoreHero.tsx": () => import("../components/mockups/session-summary/ScoreHero.tsx"),
  "./components/mockups/session-summary/TwinPanel.tsx": () => import("../components/mockups/session-summary/TwinPanel.tsx")
};
